const LOGIN_USER = "LOGIN_USER";
const LOGIN_FAILED = "LOGIN_FAILED";
const GET_POSTS = "GET_POSTS";
const GET_POSTS_FAILED = "GET_POSTS_FAILED";
const NO_POSTS = "NO_POSTS";
const NEW_POST = "NEW_POST";
const NEW_POST_FAILED = "NEW_POST_FAILED";

export {
  LOGIN_USER,
  LOGIN_FAILED,
  GET_POSTS,
  GET_POSTS_FAILED,
  NO_POSTS,
  NEW_POST,
  NEW_POST_FAILED,
};
