// get all users
GET https://localhost:443/api/users
//Authorization: jwt-token 
###
// register user "Can1"
POST https://localhost:443/api/users/register 
//Authorization: Basic RnJlZDpxd2VydHk=
content-type: application/json

{
    "username":"cancoel3",
    "password":"qwerty",
    "email":"test@wefrw2e2r.com",
    "userTypeAdmin":false
}

###
// delete user by id
DELETE https://localhost:443/api/users/remove/5eecf8cc390882b78f2f9483
Authorization: jwt-token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7InVzZXJuYW1lIjoiY2FuY29lbCIsImFkbWluIjp0cnVlfSwiaWF0IjoxNTkyNTg4NTIwLCJleHAiOjE1OTI1ODg4MjB9.50Koe6Lewux9hK_DSZ2UKnUA3juMKPyz0y3TJGnZHwM
content-type: application/json

{
    "password":"qwerty"
} 


###
// login with username and password
POST https://localhost:443/api/users/login
Authorization: Basic Y2FuY29lbDI6cXdlcnR5



###
// get user with by id
GET https://localhost:443/api/users/5f0c56a9d2718950af1a21c9
Token: jwt-token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7InVzZXJuYW1lIjoiY2FuY29lbDIiLCJhZG1pbiI6ZmFsc2V9LCJpYXQiOjE1OTQ3Mzg1MTIsImV4cCI6MTU5NDczODgxMn0.65M6OHiTv7tc0dKZTJHjLll3asEUGJQ8e5ke68UnlSs



###
// send a message to an user by recipients id
POST https://localhost:443/api/message/5ee8c4c5440d4c038b4511b1 HTTP/1.1
Content-Type: application/json

{
    "sender": "5ee8c468440d4c038b4511b0",
    "message":"Testnachricht" 
}

###
// get all messages in db
GET https://localhost:443/api/message

###
// get message by user id
GET https://localhost:443/api/message/5ee8c4c5440d4c038b4511b1

###
// delete message by message_id
DELETE https://localhost:443/api/message/remove/5ee8c50a440d4c038b4511b2

###
// post new thread
POST https://localhost:443/api/threads
Content-Type: application/json

{
    "title":"Vorstellung",
    "author": "5ee8c468440d4c038b4511b0",
    "content":"Hallo, ich bin der neue User!"
}

###
// get all existing threads
GET https://localhost:443/api/threads

###
// get thread by id
GET https://localhost:443/api/threads/5ee8c5f5440d4c038b4511b5

###
// delete thread by id
DELETE https://localhost:443/api/threads/remove/5ee8c5f5440d4c038b4511b5

###
// edit thread by id
PATCH https://localhost:443/api/threads/edit/5ee65ffd809e9551a7514b82
Content-Type: application/json

{
    "title":"hello again",
    "content":"hey, ich bins wieder!"
}

###
// get reply by id
GET https://localhost:443/api/threads/reply/5ee7a6b4abab9b6380372342

###
// post reply from a user_id
POST https://localhost:443/api/threads/5ee65ffd809e9551a7514b82/reply
